steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
  - echo "Intializing the build for the $PROJECT_ID"
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'step2'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
  - echo "My project"
- name: "gcr.io/cloud-builders/git"
  entrypoint: "sh"
  args:
    - "-c"
    - |
      git config --global user.email "suriyagsp1@gmail.com"
      git config --global user.name "SURIYAPRAKASHG"
      echo "Build completed at $(date)" >> build-status.txt
      git add build-status.txt
      git commit -m "Update build status [skip ci]"
      git push gcp-project
      git checkout gcp-project
options:
  logging: CLOUD_LOGGING_ONLY
