steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
  - echo "Intializing the build for the $PROJECT_ID"

options:
  logging: CLOUD_LOGGING_ONLY
